### ISSUE TITLE
Not showing suggestion on Sublime 4

### ISSUE THREAD

**Issue by ciaoben** [sublimelsp/LSP-tailwindcss#13]
Thanks for the work, this plugin in much needed in the sublime ecosystem.

I tried but It does not show any suggestion in Sublime 4. Is there any way to debug what is happening?
So I can help improving it.

**Comment by davidwebca** [comment]
I've been having issues with one of the last updates too, but I have a hard time pin-pointing what's happening. I can say for sure that the plugin now doesn't detect my tailwind.config.js in a sub-directory, I have to create one at the root and include / reexport it. But even then hover cards, suggestions and such don't wory anymore either 🤔

**Comment by predragnikolic** [comment]
In the README,this part here is important:
> In order for the extension to activate you must have [tailwindcss](https://tailwindcss.com/docs/installation) installed and a [Tailwind config file](https://tailwindcss.com/docs/installation#create-your-configuration-file) named `tailwind.config.js` in your workspace.

Here is a working example:

You can clone this repo https://github.com/ParamagicDev/tailwind-example
```
git clone https://github.com/ParamagicDev/tailwind-example
```

1. than run `cd tailwind-example`, then `npm i` (to install the tailwindcss(that is required for the server to work) and other deps from [package.json](https://github.com/ParamagicDev/tailwind-example/blob/master/package.json#L27)).

 
```
cd tailwind-example 
npm i 
```
2. Make sure to have  `tailwind.config.js` at the root of the opened folder. (I would need to check if the server can work if the  `tailwind.config.js` is in a sub folder. and if so I can remove this code [here](https://github.com/sublimelsp/LSP-tailwindcss/blob/master/plugin.py#L30-L36))

Than you can create an index.html file, and see if it is working. 

![image](https://user-images.githubusercontent.com/22029477/123995034-32944400-d9ce-11eb-80fc-37c653975e7b.png)

**Comment by predragnikolic** [comment]
> I can say for sure that the plugin now doesn't detect my tailwind.config.js in a sub-directory

I created a fix for that here:
https://github.com/sublimelsp/LSP-tailwindcss/pull/14

**Comment by predragnikolic** [comment]
> I can say for sure that the plugin now doesn't detect my tailwind.config.js in a sub-directory

This has been fixed and I made a release so it will be on PackageControl - https://github.com/sublimelsp/LSP-tailwindcss/releases/tag/0.0.2 @davidwebca 

@ciaoben If you still have any problems, feel free to ping me.

**Comment by davidwebca** [comment]
Yes, it works! Well... mostly. The issue remains that I have a plugin installed in my PHP project that has a tailwind.config.js file in it and sometimes it's trying to load it first and fails. Since tailwindcss is not installed there, it just crashes and doesn't move on to find my own file, but sometimes it ends up finding mine first and all is good then. 

One solution would be to not crash the process if tailwindcss is not found if possible, but the other thing is that my plugins are in my .gitignore, so maybe there's something you could do with that.

**Comment by predragnikolic** [comment]
>  it just crashes and doesn't move on to find my own file

What do you mean by "my own file"? :)
Can you take a screenshoot of the of your structure?

```
php-project/
  nested-folder/
    ...
    tailwind.config.js
  other-folder/
    ...
  tailwind.config.js 
```

**Comment by davidwebca** [comment]
I'll summarize the structure, but it's basically a WordPress project started from [Bedrocks](https://github.com/roots/bedrock) + [Sage ](https://github.com/roots/sage)

```
web/
  app/
    app/plugins/ (everything in here is git ignored)
      acf-editor-palette/
        tailwind.config.js (wrong file)
    themes/
      myproject/
        tailwind.config.js (right file)
```

So basically, the plugin has that trailing tailwind.config.js file there, but it's not mine. If the glob is alphabetical, it finds the other one first and crashes since tailwindcss is not installed there.

This is probably an edge case, but as I see it, there's either the solution of try / catching the error and continuing searching for other config files until one's found with tailwind installed in there or an extension setting that could be overridden per-project to prioritize some file locations.

**Comment by predragnikolic** [comment]
@davidwebca you can put the folder name that you want to exclude(`acf-editor-palette`) in `folder_exclude_patterns` in sublime preferences settings.

When LSP-tailwindcss looks for the tailwind config file, it takes into account `folder_exclude_patterns`. (https://github.com/sublimelsp/LSP-tailwindcss/blob/master/plugin.py#L38).

**Comment by zigi05** [comment]
I've tried with https://github.com/ParamagicDev/tailwind-example, but LSP-tailwind still not working in my Sublime Text 4. I have these last lines in the console:

````
[lsp_utils] Command output END
Traceback (most recent call last):
  File "C:\Users\username\AppData\Roaming\Sublime Text\Installed Packages\LSP.sublime-package\plugin/session_view.py", line 175, in on_capability_added_async
  File "C:\Users\username\AppData\Roaming\Sublime Text\Installed Packages\LSP.sublime-package\plugin/session_view.py", line 96, in _register_auto_complete_triggers
  File "C:\Users\username\AppData\Roaming\Sublime Text\Installed Packages\LSP.sublime-package\plugin/session_view.py", line 130, in _apply_auto_complete_triggers
TypeError: sequence item 8: expected str instance, NoneType found
````

**Comment by predragnikolic** [comment]
I will close this ticket because it starts to contain other issues that are better suited as separate tickets. 

@ciaoben if you still have a problem, 
feel free to ping me, but please provide a minimal repo repro :)
